[project]
name = "geo"
version = "0.1.0"
dependencies = ["flet", "flet-geolocator"]

[tool.flet]
main = "main.py"
permissions = ["location"]

[tool.flet.android.permission]
"android.permission.ACCESS_FINE_LOCATION" = true
"android.permission.ACCESS_COARSE_LOCATION" = true
"android.permission.ACCESS_BACKGROUND_LOCATION" = true
"android.permission.FOREGROUND_SERVICE_LOCATION" = true